// Code generated by SQLBoiler 4.16.2 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package appdb

var TableNames = struct {
	Asset             string
	BookingGroup      string
	BookingOccurrence string
	Configuration     string
	RoomBooking       string
}{
	Asset:             "asset",
	BookingGroup:      "booking_group",
	BookingOccurrence: "booking_occurrence",
	Configuration:     "configuration",
	RoomBooking:       "room_booking",
}
