// Code generated by SQLBoiler 4.16.2 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package appdb

import (
	"context"
	"database/sql"
	"fmt"
	"reflect"
	"strconv"
	"strings"
	"sync"
	"time"

	"github.com/friendsofgo/errors"
	"github.com/volatiletech/null/v8"
	"github.com/volatiletech/sqlboiler/v4/boil"
	"github.com/volatiletech/sqlboiler/v4/queries"
	"github.com/volatiletech/sqlboiler/v4/queries/qm"
	"github.com/volatiletech/sqlboiler/v4/queries/qmhelper"
	"github.com/volatiletech/strmangle"
)

// BookingOccurrence is an object representing the database table.
type BookingOccurrence struct {
	ID                    int64      `boil:"id" json:"id" toml:"id" yaml:"id"`
	BookingGroupID        int64      `boil:"booking_group_id" json:"booking_group_id" toml:"booking_group_id" yaml:"booking_group_id"`
	ExchangeInstanceIndex int32      `boil:"exchange_instance_index" json:"exchange_instance_index" toml:"exchange_instance_index" yaml:"exchange_instance_index"`
	ElionaBookingID       null.Int32 `boil:"eliona_booking_id" json:"eliona_booking_id,omitempty" toml:"eliona_booking_id" yaml:"eliona_booking_id,omitempty"`

	R *bookingOccurrenceR `boil:"-" json:"-" toml:"-" yaml:"-"`
	L bookingOccurrenceL  `boil:"-" json:"-" toml:"-" yaml:"-"`
}

var BookingOccurrenceColumns = struct {
	ID                    string
	BookingGroupID        string
	ExchangeInstanceIndex string
	ElionaBookingID       string
}{
	ID:                    "id",
	BookingGroupID:        "booking_group_id",
	ExchangeInstanceIndex: "exchange_instance_index",
	ElionaBookingID:       "eliona_booking_id",
}

var BookingOccurrenceTableColumns = struct {
	ID                    string
	BookingGroupID        string
	ExchangeInstanceIndex string
	ElionaBookingID       string
}{
	ID:                    "booking_occurrence.id",
	BookingGroupID:        "booking_occurrence.booking_group_id",
	ExchangeInstanceIndex: "booking_occurrence.exchange_instance_index",
	ElionaBookingID:       "booking_occurrence.eliona_booking_id",
}

// Generated where

type whereHelperint32 struct{ field string }

func (w whereHelperint32) EQ(x int32) qm.QueryMod  { return qmhelper.Where(w.field, qmhelper.EQ, x) }
func (w whereHelperint32) NEQ(x int32) qm.QueryMod { return qmhelper.Where(w.field, qmhelper.NEQ, x) }
func (w whereHelperint32) LT(x int32) qm.QueryMod  { return qmhelper.Where(w.field, qmhelper.LT, x) }
func (w whereHelperint32) LTE(x int32) qm.QueryMod { return qmhelper.Where(w.field, qmhelper.LTE, x) }
func (w whereHelperint32) GT(x int32) qm.QueryMod  { return qmhelper.Where(w.field, qmhelper.GT, x) }
func (w whereHelperint32) GTE(x int32) qm.QueryMod { return qmhelper.Where(w.field, qmhelper.GTE, x) }
func (w whereHelperint32) IN(slice []int32) qm.QueryMod {
	values := make([]interface{}, 0, len(slice))
	for _, value := range slice {
		values = append(values, value)
	}
	return qm.WhereIn(fmt.Sprintf("%s IN ?", w.field), values...)
}
func (w whereHelperint32) NIN(slice []int32) qm.QueryMod {
	values := make([]interface{}, 0, len(slice))
	for _, value := range slice {
		values = append(values, value)
	}
	return qm.WhereNotIn(fmt.Sprintf("%s NOT IN ?", w.field), values...)
}

var BookingOccurrenceWhere = struct {
	ID                    whereHelperint64
	BookingGroupID        whereHelperint64
	ExchangeInstanceIndex whereHelperint32
	ElionaBookingID       whereHelpernull_Int32
}{
	ID:                    whereHelperint64{field: "\"ews\".\"booking_occurrence\".\"id\""},
	BookingGroupID:        whereHelperint64{field: "\"ews\".\"booking_occurrence\".\"booking_group_id\""},
	ExchangeInstanceIndex: whereHelperint32{field: "\"ews\".\"booking_occurrence\".\"exchange_instance_index\""},
	ElionaBookingID:       whereHelpernull_Int32{field: "\"ews\".\"booking_occurrence\".\"eliona_booking_id\""},
}

// BookingOccurrenceRels is where relationship names are stored.
var BookingOccurrenceRels = struct {
	BookingGroup string
	RoomBookings string
}{
	BookingGroup: "BookingGroup",
	RoomBookings: "RoomBookings",
}

// bookingOccurrenceR is where relationships are stored.
type bookingOccurrenceR struct {
	BookingGroup *BookingGroup    `boil:"BookingGroup" json:"BookingGroup" toml:"BookingGroup" yaml:"BookingGroup"`
	RoomBookings RoomBookingSlice `boil:"RoomBookings" json:"RoomBookings" toml:"RoomBookings" yaml:"RoomBookings"`
}

// NewStruct creates a new relationship struct
func (*bookingOccurrenceR) NewStruct() *bookingOccurrenceR {
	return &bookingOccurrenceR{}
}

func (r *bookingOccurrenceR) GetBookingGroup() *BookingGroup {
	if r == nil {
		return nil
	}
	return r.BookingGroup
}

func (r *bookingOccurrenceR) GetRoomBookings() RoomBookingSlice {
	if r == nil {
		return nil
	}
	return r.RoomBookings
}

// bookingOccurrenceL is where Load methods for each relationship are stored.
type bookingOccurrenceL struct{}

var (
	bookingOccurrenceAllColumns            = []string{"id", "booking_group_id", "exchange_instance_index", "eliona_booking_id"}
	bookingOccurrenceColumnsWithoutDefault = []string{"exchange_instance_index"}
	bookingOccurrenceColumnsWithDefault    = []string{"id", "booking_group_id", "eliona_booking_id"}
	bookingOccurrencePrimaryKeyColumns     = []string{"id"}
	bookingOccurrenceGeneratedColumns      = []string{}
)

type (
	// BookingOccurrenceSlice is an alias for a slice of pointers to BookingOccurrence.
	// This should almost always be used instead of []BookingOccurrence.
	BookingOccurrenceSlice []*BookingOccurrence
	// BookingOccurrenceHook is the signature for custom BookingOccurrence hook methods
	BookingOccurrenceHook func(context.Context, boil.ContextExecutor, *BookingOccurrence) error

	bookingOccurrenceQuery struct {
		*queries.Query
	}
)

// Cache for insert, update and upsert
var (
	bookingOccurrenceType                 = reflect.TypeOf(&BookingOccurrence{})
	bookingOccurrenceMapping              = queries.MakeStructMapping(bookingOccurrenceType)
	bookingOccurrencePrimaryKeyMapping, _ = queries.BindMapping(bookingOccurrenceType, bookingOccurrenceMapping, bookingOccurrencePrimaryKeyColumns)
	bookingOccurrenceInsertCacheMut       sync.RWMutex
	bookingOccurrenceInsertCache          = make(map[string]insertCache)
	bookingOccurrenceUpdateCacheMut       sync.RWMutex
	bookingOccurrenceUpdateCache          = make(map[string]updateCache)
	bookingOccurrenceUpsertCacheMut       sync.RWMutex
	bookingOccurrenceUpsertCache          = make(map[string]insertCache)
)

var (
	// Force time package dependency for automated UpdatedAt/CreatedAt.
	_ = time.Second
	// Force qmhelper dependency for where clause generation (which doesn't
	// always happen)
	_ = qmhelper.Where
)

var bookingOccurrenceAfterSelectMu sync.Mutex
var bookingOccurrenceAfterSelectHooks []BookingOccurrenceHook

var bookingOccurrenceBeforeInsertMu sync.Mutex
var bookingOccurrenceBeforeInsertHooks []BookingOccurrenceHook
var bookingOccurrenceAfterInsertMu sync.Mutex
var bookingOccurrenceAfterInsertHooks []BookingOccurrenceHook

var bookingOccurrenceBeforeUpdateMu sync.Mutex
var bookingOccurrenceBeforeUpdateHooks []BookingOccurrenceHook
var bookingOccurrenceAfterUpdateMu sync.Mutex
var bookingOccurrenceAfterUpdateHooks []BookingOccurrenceHook

var bookingOccurrenceBeforeDeleteMu sync.Mutex
var bookingOccurrenceBeforeDeleteHooks []BookingOccurrenceHook
var bookingOccurrenceAfterDeleteMu sync.Mutex
var bookingOccurrenceAfterDeleteHooks []BookingOccurrenceHook

var bookingOccurrenceBeforeUpsertMu sync.Mutex
var bookingOccurrenceBeforeUpsertHooks []BookingOccurrenceHook
var bookingOccurrenceAfterUpsertMu sync.Mutex
var bookingOccurrenceAfterUpsertHooks []BookingOccurrenceHook

// doAfterSelectHooks executes all "after Select" hooks.
func (o *BookingOccurrence) doAfterSelectHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range bookingOccurrenceAfterSelectHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeInsertHooks executes all "before insert" hooks.
func (o *BookingOccurrence) doBeforeInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range bookingOccurrenceBeforeInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterInsertHooks executes all "after Insert" hooks.
func (o *BookingOccurrence) doAfterInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range bookingOccurrenceAfterInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpdateHooks executes all "before Update" hooks.
func (o *BookingOccurrence) doBeforeUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range bookingOccurrenceBeforeUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpdateHooks executes all "after Update" hooks.
func (o *BookingOccurrence) doAfterUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range bookingOccurrenceAfterUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeDeleteHooks executes all "before Delete" hooks.
func (o *BookingOccurrence) doBeforeDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range bookingOccurrenceBeforeDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterDeleteHooks executes all "after Delete" hooks.
func (o *BookingOccurrence) doAfterDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range bookingOccurrenceAfterDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpsertHooks executes all "before Upsert" hooks.
func (o *BookingOccurrence) doBeforeUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range bookingOccurrenceBeforeUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpsertHooks executes all "after Upsert" hooks.
func (o *BookingOccurrence) doAfterUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range bookingOccurrenceAfterUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// AddBookingOccurrenceHook registers your hook function for all future operations.
func AddBookingOccurrenceHook(hookPoint boil.HookPoint, bookingOccurrenceHook BookingOccurrenceHook) {
	switch hookPoint {
	case boil.AfterSelectHook:
		bookingOccurrenceAfterSelectMu.Lock()
		bookingOccurrenceAfterSelectHooks = append(bookingOccurrenceAfterSelectHooks, bookingOccurrenceHook)
		bookingOccurrenceAfterSelectMu.Unlock()
	case boil.BeforeInsertHook:
		bookingOccurrenceBeforeInsertMu.Lock()
		bookingOccurrenceBeforeInsertHooks = append(bookingOccurrenceBeforeInsertHooks, bookingOccurrenceHook)
		bookingOccurrenceBeforeInsertMu.Unlock()
	case boil.AfterInsertHook:
		bookingOccurrenceAfterInsertMu.Lock()
		bookingOccurrenceAfterInsertHooks = append(bookingOccurrenceAfterInsertHooks, bookingOccurrenceHook)
		bookingOccurrenceAfterInsertMu.Unlock()
	case boil.BeforeUpdateHook:
		bookingOccurrenceBeforeUpdateMu.Lock()
		bookingOccurrenceBeforeUpdateHooks = append(bookingOccurrenceBeforeUpdateHooks, bookingOccurrenceHook)
		bookingOccurrenceBeforeUpdateMu.Unlock()
	case boil.AfterUpdateHook:
		bookingOccurrenceAfterUpdateMu.Lock()
		bookingOccurrenceAfterUpdateHooks = append(bookingOccurrenceAfterUpdateHooks, bookingOccurrenceHook)
		bookingOccurrenceAfterUpdateMu.Unlock()
	case boil.BeforeDeleteHook:
		bookingOccurrenceBeforeDeleteMu.Lock()
		bookingOccurrenceBeforeDeleteHooks = append(bookingOccurrenceBeforeDeleteHooks, bookingOccurrenceHook)
		bookingOccurrenceBeforeDeleteMu.Unlock()
	case boil.AfterDeleteHook:
		bookingOccurrenceAfterDeleteMu.Lock()
		bookingOccurrenceAfterDeleteHooks = append(bookingOccurrenceAfterDeleteHooks, bookingOccurrenceHook)
		bookingOccurrenceAfterDeleteMu.Unlock()
	case boil.BeforeUpsertHook:
		bookingOccurrenceBeforeUpsertMu.Lock()
		bookingOccurrenceBeforeUpsertHooks = append(bookingOccurrenceBeforeUpsertHooks, bookingOccurrenceHook)
		bookingOccurrenceBeforeUpsertMu.Unlock()
	case boil.AfterUpsertHook:
		bookingOccurrenceAfterUpsertMu.Lock()
		bookingOccurrenceAfterUpsertHooks = append(bookingOccurrenceAfterUpsertHooks, bookingOccurrenceHook)
		bookingOccurrenceAfterUpsertMu.Unlock()
	}
}

// OneG returns a single bookingOccurrence record from the query using the global executor.
func (q bookingOccurrenceQuery) OneG(ctx context.Context) (*BookingOccurrence, error) {
	return q.One(ctx, boil.GetContextDB())
}

// One returns a single bookingOccurrence record from the query.
func (q bookingOccurrenceQuery) One(ctx context.Context, exec boil.ContextExecutor) (*BookingOccurrence, error) {
	o := &BookingOccurrence{}

	queries.SetLimit(q.Query, 1)

	err := q.Bind(ctx, exec, o)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "appdb: failed to execute a one query for booking_occurrence")
	}

	if err := o.doAfterSelectHooks(ctx, exec); err != nil {
		return o, err
	}

	return o, nil
}

// AllG returns all BookingOccurrence records from the query using the global executor.
func (q bookingOccurrenceQuery) AllG(ctx context.Context) (BookingOccurrenceSlice, error) {
	return q.All(ctx, boil.GetContextDB())
}

// All returns all BookingOccurrence records from the query.
func (q bookingOccurrenceQuery) All(ctx context.Context, exec boil.ContextExecutor) (BookingOccurrenceSlice, error) {
	var o []*BookingOccurrence

	err := q.Bind(ctx, exec, &o)
	if err != nil {
		return nil, errors.Wrap(err, "appdb: failed to assign all query results to BookingOccurrence slice")
	}

	if len(bookingOccurrenceAfterSelectHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterSelectHooks(ctx, exec); err != nil {
				return o, err
			}
		}
	}

	return o, nil
}

// CountG returns the count of all BookingOccurrence records in the query using the global executor
func (q bookingOccurrenceQuery) CountG(ctx context.Context) (int64, error) {
	return q.Count(ctx, boil.GetContextDB())
}

// Count returns the count of all BookingOccurrence records in the query.
func (q bookingOccurrenceQuery) Count(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return 0, errors.Wrap(err, "appdb: failed to count booking_occurrence rows")
	}

	return count, nil
}

// ExistsG checks if the row exists in the table using the global executor.
func (q bookingOccurrenceQuery) ExistsG(ctx context.Context) (bool, error) {
	return q.Exists(ctx, boil.GetContextDB())
}

// Exists checks if the row exists in the table.
func (q bookingOccurrenceQuery) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)
	queries.SetLimit(q.Query, 1)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return false, errors.Wrap(err, "appdb: failed to check if booking_occurrence exists")
	}

	return count > 0, nil
}

// BookingGroup pointed to by the foreign key.
func (o *BookingOccurrence) BookingGroup(mods ...qm.QueryMod) bookingGroupQuery {
	queryMods := []qm.QueryMod{
		qm.Where("\"id\" = ?", o.BookingGroupID),
	}

	queryMods = append(queryMods, mods...)

	return BookingGroups(queryMods...)
}

// RoomBookings retrieves all the room_booking's RoomBookings with an executor.
func (o *BookingOccurrence) RoomBookings(mods ...qm.QueryMod) roomBookingQuery {
	var queryMods []qm.QueryMod
	if len(mods) != 0 {
		queryMods = append(queryMods, mods...)
	}

	queryMods = append(queryMods,
		qm.Where("\"ews\".\"room_booking\".\"booking_occurrence_id\"=?", o.ID),
	)

	return RoomBookings(queryMods...)
}

// LoadBookingGroup allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for an N-1 relationship.
func (bookingOccurrenceL) LoadBookingGroup(ctx context.Context, e boil.ContextExecutor, singular bool, maybeBookingOccurrence interface{}, mods queries.Applicator) error {
	var slice []*BookingOccurrence
	var object *BookingOccurrence

	if singular {
		var ok bool
		object, ok = maybeBookingOccurrence.(*BookingOccurrence)
		if !ok {
			object = new(BookingOccurrence)
			ok = queries.SetFromEmbeddedStruct(&object, &maybeBookingOccurrence)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", object, maybeBookingOccurrence))
			}
		}
	} else {
		s, ok := maybeBookingOccurrence.(*[]*BookingOccurrence)
		if ok {
			slice = *s
		} else {
			ok = queries.SetFromEmbeddedStruct(&slice, maybeBookingOccurrence)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", slice, maybeBookingOccurrence))
			}
		}
	}

	args := make(map[interface{}]struct{})
	if singular {
		if object.R == nil {
			object.R = &bookingOccurrenceR{}
		}
		args[object.BookingGroupID] = struct{}{}

	} else {
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &bookingOccurrenceR{}
			}

			args[obj.BookingGroupID] = struct{}{}

		}
	}

	if len(args) == 0 {
		return nil
	}

	argsSlice := make([]interface{}, len(args))
	i := 0
	for arg := range args {
		argsSlice[i] = arg
		i++
	}

	query := NewQuery(
		qm.From(`ews.booking_group`),
		qm.WhereIn(`ews.booking_group.id in ?`, argsSlice...),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load BookingGroup")
	}

	var resultSlice []*BookingGroup
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice BookingGroup")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results of eager load for booking_group")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for booking_group")
	}

	if len(bookingGroupAfterSelectHooks) != 0 {
		for _, obj := range resultSlice {
			if err := obj.doAfterSelectHooks(ctx, e); err != nil {
				return err
			}
		}
	}

	if len(resultSlice) == 0 {
		return nil
	}

	if singular {
		foreign := resultSlice[0]
		object.R.BookingGroup = foreign
		if foreign.R == nil {
			foreign.R = &bookingGroupR{}
		}
		foreign.R.BookingOccurrences = append(foreign.R.BookingOccurrences, object)
		return nil
	}

	for _, local := range slice {
		for _, foreign := range resultSlice {
			if local.BookingGroupID == foreign.ID {
				local.R.BookingGroup = foreign
				if foreign.R == nil {
					foreign.R = &bookingGroupR{}
				}
				foreign.R.BookingOccurrences = append(foreign.R.BookingOccurrences, local)
				break
			}
		}
	}

	return nil
}

// LoadRoomBookings allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for a 1-M or N-M relationship.
func (bookingOccurrenceL) LoadRoomBookings(ctx context.Context, e boil.ContextExecutor, singular bool, maybeBookingOccurrence interface{}, mods queries.Applicator) error {
	var slice []*BookingOccurrence
	var object *BookingOccurrence

	if singular {
		var ok bool
		object, ok = maybeBookingOccurrence.(*BookingOccurrence)
		if !ok {
			object = new(BookingOccurrence)
			ok = queries.SetFromEmbeddedStruct(&object, &maybeBookingOccurrence)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", object, maybeBookingOccurrence))
			}
		}
	} else {
		s, ok := maybeBookingOccurrence.(*[]*BookingOccurrence)
		if ok {
			slice = *s
		} else {
			ok = queries.SetFromEmbeddedStruct(&slice, maybeBookingOccurrence)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", slice, maybeBookingOccurrence))
			}
		}
	}

	args := make(map[interface{}]struct{})
	if singular {
		if object.R == nil {
			object.R = &bookingOccurrenceR{}
		}
		args[object.ID] = struct{}{}
	} else {
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &bookingOccurrenceR{}
			}
			args[obj.ID] = struct{}{}
		}
	}

	if len(args) == 0 {
		return nil
	}

	argsSlice := make([]interface{}, len(args))
	i := 0
	for arg := range args {
		argsSlice[i] = arg
		i++
	}

	query := NewQuery(
		qm.From(`ews.room_booking`),
		qm.WhereIn(`ews.room_booking.booking_occurrence_id in ?`, argsSlice...),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load room_booking")
	}

	var resultSlice []*RoomBooking
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice room_booking")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results in eager load on room_booking")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for room_booking")
	}

	if len(roomBookingAfterSelectHooks) != 0 {
		for _, obj := range resultSlice {
			if err := obj.doAfterSelectHooks(ctx, e); err != nil {
				return err
			}
		}
	}
	if singular {
		object.R.RoomBookings = resultSlice
		for _, foreign := range resultSlice {
			if foreign.R == nil {
				foreign.R = &roomBookingR{}
			}
			foreign.R.BookingOccurrence = object
		}
		return nil
	}

	for _, foreign := range resultSlice {
		for _, local := range slice {
			if local.ID == foreign.BookingOccurrenceID {
				local.R.RoomBookings = append(local.R.RoomBookings, foreign)
				if foreign.R == nil {
					foreign.R = &roomBookingR{}
				}
				foreign.R.BookingOccurrence = local
				break
			}
		}
	}

	return nil
}

// SetBookingGroupG of the bookingOccurrence to the related item.
// Sets o.R.BookingGroup to related.
// Adds o to related.R.BookingOccurrences.
// Uses the global database handle.
func (o *BookingOccurrence) SetBookingGroupG(ctx context.Context, insert bool, related *BookingGroup) error {
	return o.SetBookingGroup(ctx, boil.GetContextDB(), insert, related)
}

// SetBookingGroup of the bookingOccurrence to the related item.
// Sets o.R.BookingGroup to related.
// Adds o to related.R.BookingOccurrences.
func (o *BookingOccurrence) SetBookingGroup(ctx context.Context, exec boil.ContextExecutor, insert bool, related *BookingGroup) error {
	var err error
	if insert {
		if err = related.Insert(ctx, exec, boil.Infer()); err != nil {
			return errors.Wrap(err, "failed to insert into foreign table")
		}
	}

	updateQuery := fmt.Sprintf(
		"UPDATE \"ews\".\"booking_occurrence\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, []string{"booking_group_id"}),
		strmangle.WhereClause("\"", "\"", 2, bookingOccurrencePrimaryKeyColumns),
	)
	values := []interface{}{related.ID, o.ID}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, updateQuery)
		fmt.Fprintln(writer, values)
	}
	if _, err = exec.ExecContext(ctx, updateQuery, values...); err != nil {
		return errors.Wrap(err, "failed to update local table")
	}

	o.BookingGroupID = related.ID
	if o.R == nil {
		o.R = &bookingOccurrenceR{
			BookingGroup: related,
		}
	} else {
		o.R.BookingGroup = related
	}

	if related.R == nil {
		related.R = &bookingGroupR{
			BookingOccurrences: BookingOccurrenceSlice{o},
		}
	} else {
		related.R.BookingOccurrences = append(related.R.BookingOccurrences, o)
	}

	return nil
}

// AddRoomBookingsG adds the given related objects to the existing relationships
// of the booking_occurrence, optionally inserting them as new records.
// Appends related to o.R.RoomBookings.
// Sets related.R.BookingOccurrence appropriately.
// Uses the global database handle.
func (o *BookingOccurrence) AddRoomBookingsG(ctx context.Context, insert bool, related ...*RoomBooking) error {
	return o.AddRoomBookings(ctx, boil.GetContextDB(), insert, related...)
}

// AddRoomBookings adds the given related objects to the existing relationships
// of the booking_occurrence, optionally inserting them as new records.
// Appends related to o.R.RoomBookings.
// Sets related.R.BookingOccurrence appropriately.
func (o *BookingOccurrence) AddRoomBookings(ctx context.Context, exec boil.ContextExecutor, insert bool, related ...*RoomBooking) error {
	var err error
	for _, rel := range related {
		if insert {
			rel.BookingOccurrenceID = o.ID
			if err = rel.Insert(ctx, exec, boil.Infer()); err != nil {
				return errors.Wrap(err, "failed to insert into foreign table")
			}
		} else {
			updateQuery := fmt.Sprintf(
				"UPDATE \"ews\".\"room_booking\" SET %s WHERE %s",
				strmangle.SetParamNames("\"", "\"", 1, []string{"booking_occurrence_id"}),
				strmangle.WhereClause("\"", "\"", 2, roomBookingPrimaryKeyColumns),
			)
			values := []interface{}{o.ID, rel.ID}

			if boil.IsDebug(ctx) {
				writer := boil.DebugWriterFrom(ctx)
				fmt.Fprintln(writer, updateQuery)
				fmt.Fprintln(writer, values)
			}
			if _, err = exec.ExecContext(ctx, updateQuery, values...); err != nil {
				return errors.Wrap(err, "failed to update foreign table")
			}

			rel.BookingOccurrenceID = o.ID
		}
	}

	if o.R == nil {
		o.R = &bookingOccurrenceR{
			RoomBookings: related,
		}
	} else {
		o.R.RoomBookings = append(o.R.RoomBookings, related...)
	}

	for _, rel := range related {
		if rel.R == nil {
			rel.R = &roomBookingR{
				BookingOccurrence: o,
			}
		} else {
			rel.R.BookingOccurrence = o
		}
	}
	return nil
}

// BookingOccurrences retrieves all the records using an executor.
func BookingOccurrences(mods ...qm.QueryMod) bookingOccurrenceQuery {
	mods = append(mods, qm.From("\"ews\".\"booking_occurrence\""))
	q := NewQuery(mods...)
	if len(queries.GetSelect(q)) == 0 {
		queries.SetSelect(q, []string{"\"ews\".\"booking_occurrence\".*"})
	}

	return bookingOccurrenceQuery{q}
}

// FindBookingOccurrenceG retrieves a single record by ID.
func FindBookingOccurrenceG(ctx context.Context, iD int64, selectCols ...string) (*BookingOccurrence, error) {
	return FindBookingOccurrence(ctx, boil.GetContextDB(), iD, selectCols...)
}

// FindBookingOccurrence retrieves a single record by ID with an executor.
// If selectCols is empty Find will return all columns.
func FindBookingOccurrence(ctx context.Context, exec boil.ContextExecutor, iD int64, selectCols ...string) (*BookingOccurrence, error) {
	bookingOccurrenceObj := &BookingOccurrence{}

	sel := "*"
	if len(selectCols) > 0 {
		sel = strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, selectCols), ",")
	}
	query := fmt.Sprintf(
		"select %s from \"ews\".\"booking_occurrence\" where \"id\"=$1", sel,
	)

	q := queries.Raw(query, iD)

	err := q.Bind(ctx, exec, bookingOccurrenceObj)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "appdb: unable to select from booking_occurrence")
	}

	if err = bookingOccurrenceObj.doAfterSelectHooks(ctx, exec); err != nil {
		return bookingOccurrenceObj, err
	}

	return bookingOccurrenceObj, nil
}

// InsertG a single record. See Insert for whitelist behavior description.
func (o *BookingOccurrence) InsertG(ctx context.Context, columns boil.Columns) error {
	return o.Insert(ctx, boil.GetContextDB(), columns)
}

// Insert a single record using an executor.
// See boil.Columns.InsertColumnSet documentation to understand column list inference for inserts.
func (o *BookingOccurrence) Insert(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) error {
	if o == nil {
		return errors.New("appdb: no booking_occurrence provided for insertion")
	}

	var err error

	if err := o.doBeforeInsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(bookingOccurrenceColumnsWithDefault, o)

	key := makeCacheKey(columns, nzDefaults)
	bookingOccurrenceInsertCacheMut.RLock()
	cache, cached := bookingOccurrenceInsertCache[key]
	bookingOccurrenceInsertCacheMut.RUnlock()

	if !cached {
		wl, returnColumns := columns.InsertColumnSet(
			bookingOccurrenceAllColumns,
			bookingOccurrenceColumnsWithDefault,
			bookingOccurrenceColumnsWithoutDefault,
			nzDefaults,
		)

		cache.valueMapping, err = queries.BindMapping(bookingOccurrenceType, bookingOccurrenceMapping, wl)
		if err != nil {
			return err
		}
		cache.retMapping, err = queries.BindMapping(bookingOccurrenceType, bookingOccurrenceMapping, returnColumns)
		if err != nil {
			return err
		}
		if len(wl) != 0 {
			cache.query = fmt.Sprintf("INSERT INTO \"ews\".\"booking_occurrence\" (\"%s\") %%sVALUES (%s)%%s", strings.Join(wl, "\",\""), strmangle.Placeholders(dialect.UseIndexPlaceholders, len(wl), 1, 1))
		} else {
			cache.query = "INSERT INTO \"ews\".\"booking_occurrence\" %sDEFAULT VALUES%s"
		}

		var queryOutput, queryReturning string

		if len(cache.retMapping) != 0 {
			queryReturning = fmt.Sprintf(" RETURNING \"%s\"", strings.Join(returnColumns, "\",\""))
		}

		cache.query = fmt.Sprintf(cache.query, queryOutput, queryReturning)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}

	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(queries.PtrsFromMapping(value, cache.retMapping)...)
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}

	if err != nil {
		return errors.Wrap(err, "appdb: unable to insert into booking_occurrence")
	}

	if !cached {
		bookingOccurrenceInsertCacheMut.Lock()
		bookingOccurrenceInsertCache[key] = cache
		bookingOccurrenceInsertCacheMut.Unlock()
	}

	return o.doAfterInsertHooks(ctx, exec)
}

// UpdateG a single BookingOccurrence record using the global executor.
// See Update for more documentation.
func (o *BookingOccurrence) UpdateG(ctx context.Context, columns boil.Columns) (int64, error) {
	return o.Update(ctx, boil.GetContextDB(), columns)
}

// Update uses an executor to update the BookingOccurrence.
// See boil.Columns.UpdateColumnSet documentation to understand column list inference for updates.
// Update does not automatically update the record in case of default values. Use .Reload() to refresh the records.
func (o *BookingOccurrence) Update(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) (int64, error) {
	var err error
	if err = o.doBeforeUpdateHooks(ctx, exec); err != nil {
		return 0, err
	}
	key := makeCacheKey(columns, nil)
	bookingOccurrenceUpdateCacheMut.RLock()
	cache, cached := bookingOccurrenceUpdateCache[key]
	bookingOccurrenceUpdateCacheMut.RUnlock()

	if !cached {
		wl := columns.UpdateColumnSet(
			bookingOccurrenceAllColumns,
			bookingOccurrencePrimaryKeyColumns,
		)

		if !columns.IsWhitelist() {
			wl = strmangle.SetComplement(wl, []string{"created_at"})
		}
		if len(wl) == 0 {
			return 0, errors.New("appdb: unable to update booking_occurrence, could not build whitelist")
		}

		cache.query = fmt.Sprintf("UPDATE \"ews\".\"booking_occurrence\" SET %s WHERE %s",
			strmangle.SetParamNames("\"", "\"", 1, wl),
			strmangle.WhereClause("\"", "\"", len(wl)+1, bookingOccurrencePrimaryKeyColumns),
		)
		cache.valueMapping, err = queries.BindMapping(bookingOccurrenceType, bookingOccurrenceMapping, append(wl, bookingOccurrencePrimaryKeyColumns...))
		if err != nil {
			return 0, err
		}
	}

	values := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, values)
	}
	var result sql.Result
	result, err = exec.ExecContext(ctx, cache.query, values...)
	if err != nil {
		return 0, errors.Wrap(err, "appdb: unable to update booking_occurrence row")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "appdb: failed to get rows affected by update for booking_occurrence")
	}

	if !cached {
		bookingOccurrenceUpdateCacheMut.Lock()
		bookingOccurrenceUpdateCache[key] = cache
		bookingOccurrenceUpdateCacheMut.Unlock()
	}

	return rowsAff, o.doAfterUpdateHooks(ctx, exec)
}

// UpdateAllG updates all rows with the specified column values.
func (q bookingOccurrenceQuery) UpdateAllG(ctx context.Context, cols M) (int64, error) {
	return q.UpdateAll(ctx, boil.GetContextDB(), cols)
}

// UpdateAll updates all rows with the specified column values.
func (q bookingOccurrenceQuery) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	queries.SetUpdate(q.Query, cols)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "appdb: unable to update all for booking_occurrence")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "appdb: unable to retrieve rows affected for booking_occurrence")
	}

	return rowsAff, nil
}

// UpdateAllG updates all rows with the specified column values.
func (o BookingOccurrenceSlice) UpdateAllG(ctx context.Context, cols M) (int64, error) {
	return o.UpdateAll(ctx, boil.GetContextDB(), cols)
}

// UpdateAll updates all rows with the specified column values, using an executor.
func (o BookingOccurrenceSlice) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	ln := int64(len(o))
	if ln == 0 {
		return 0, nil
	}

	if len(cols) == 0 {
		return 0, errors.New("appdb: update all requires at least one column argument")
	}

	colNames := make([]string, len(cols))
	args := make([]interface{}, len(cols))

	i := 0
	for name, value := range cols {
		colNames[i] = name
		args[i] = value
		i++
	}

	// Append all of the primary key values for each column
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), bookingOccurrencePrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := fmt.Sprintf("UPDATE \"ews\".\"booking_occurrence\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, colNames),
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), len(colNames)+1, bookingOccurrencePrimaryKeyColumns, len(o)))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "appdb: unable to update all in bookingOccurrence slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "appdb: unable to retrieve rows affected all in update all bookingOccurrence")
	}
	return rowsAff, nil
}

// UpsertG attempts an insert, and does an update or ignore on conflict.
func (o *BookingOccurrence) UpsertG(ctx context.Context, updateOnConflict bool, conflictColumns []string, updateColumns, insertColumns boil.Columns, opts ...UpsertOptionFunc) error {
	return o.Upsert(ctx, boil.GetContextDB(), updateOnConflict, conflictColumns, updateColumns, insertColumns, opts...)
}

// Upsert attempts an insert using an executor, and does an update or ignore on conflict.
// See boil.Columns documentation for how to properly use updateColumns and insertColumns.
func (o *BookingOccurrence) Upsert(ctx context.Context, exec boil.ContextExecutor, updateOnConflict bool, conflictColumns []string, updateColumns, insertColumns boil.Columns, opts ...UpsertOptionFunc) error {
	if o == nil {
		return errors.New("appdb: no booking_occurrence provided for upsert")
	}

	if err := o.doBeforeUpsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(bookingOccurrenceColumnsWithDefault, o)

	// Build cache key in-line uglily - mysql vs psql problems
	buf := strmangle.GetBuffer()
	if updateOnConflict {
		buf.WriteByte('t')
	} else {
		buf.WriteByte('f')
	}
	buf.WriteByte('.')
	for _, c := range conflictColumns {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(updateColumns.Kind))
	for _, c := range updateColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(insertColumns.Kind))
	for _, c := range insertColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range nzDefaults {
		buf.WriteString(c)
	}
	key := buf.String()
	strmangle.PutBuffer(buf)

	bookingOccurrenceUpsertCacheMut.RLock()
	cache, cached := bookingOccurrenceUpsertCache[key]
	bookingOccurrenceUpsertCacheMut.RUnlock()

	var err error

	if !cached {
		insert, _ := insertColumns.InsertColumnSet(
			bookingOccurrenceAllColumns,
			bookingOccurrenceColumnsWithDefault,
			bookingOccurrenceColumnsWithoutDefault,
			nzDefaults,
		)

		update := updateColumns.UpdateColumnSet(
			bookingOccurrenceAllColumns,
			bookingOccurrencePrimaryKeyColumns,
		)

		if updateOnConflict && len(update) == 0 {
			return errors.New("appdb: unable to upsert booking_occurrence, could not build update column list")
		}

		ret := strmangle.SetComplement(bookingOccurrenceAllColumns, strmangle.SetIntersect(insert, update))

		conflict := conflictColumns
		if len(conflict) == 0 && updateOnConflict && len(update) != 0 {
			if len(bookingOccurrencePrimaryKeyColumns) == 0 {
				return errors.New("appdb: unable to upsert booking_occurrence, could not build conflict column list")
			}

			conflict = make([]string, len(bookingOccurrencePrimaryKeyColumns))
			copy(conflict, bookingOccurrencePrimaryKeyColumns)
		}
		cache.query = buildUpsertQueryPostgres(dialect, "\"ews\".\"booking_occurrence\"", updateOnConflict, ret, update, conflict, insert, opts...)

		cache.valueMapping, err = queries.BindMapping(bookingOccurrenceType, bookingOccurrenceMapping, insert)
		if err != nil {
			return err
		}
		if len(ret) != 0 {
			cache.retMapping, err = queries.BindMapping(bookingOccurrenceType, bookingOccurrenceMapping, ret)
			if err != nil {
				return err
			}
		}
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)
	var returns []interface{}
	if len(cache.retMapping) != 0 {
		returns = queries.PtrsFromMapping(value, cache.retMapping)
	}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}
	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(returns...)
		if errors.Is(err, sql.ErrNoRows) {
			err = nil // Postgres doesn't return anything when there's no update
		}
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}
	if err != nil {
		return errors.Wrap(err, "appdb: unable to upsert booking_occurrence")
	}

	if !cached {
		bookingOccurrenceUpsertCacheMut.Lock()
		bookingOccurrenceUpsertCache[key] = cache
		bookingOccurrenceUpsertCacheMut.Unlock()
	}

	return o.doAfterUpsertHooks(ctx, exec)
}

// DeleteG deletes a single BookingOccurrence record.
// DeleteG will match against the primary key column to find the record to delete.
func (o *BookingOccurrence) DeleteG(ctx context.Context) (int64, error) {
	return o.Delete(ctx, boil.GetContextDB())
}

// Delete deletes a single BookingOccurrence record with an executor.
// Delete will match against the primary key column to find the record to delete.
func (o *BookingOccurrence) Delete(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if o == nil {
		return 0, errors.New("appdb: no BookingOccurrence provided for delete")
	}

	if err := o.doBeforeDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	args := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), bookingOccurrencePrimaryKeyMapping)
	sql := "DELETE FROM \"ews\".\"booking_occurrence\" WHERE \"id\"=$1"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "appdb: unable to delete from booking_occurrence")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "appdb: failed to get rows affected by delete for booking_occurrence")
	}

	if err := o.doAfterDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	return rowsAff, nil
}

func (q bookingOccurrenceQuery) DeleteAllG(ctx context.Context) (int64, error) {
	return q.DeleteAll(ctx, boil.GetContextDB())
}

// DeleteAll deletes all matching rows.
func (q bookingOccurrenceQuery) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if q.Query == nil {
		return 0, errors.New("appdb: no bookingOccurrenceQuery provided for delete all")
	}

	queries.SetDelete(q.Query)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "appdb: unable to delete all from booking_occurrence")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "appdb: failed to get rows affected by deleteall for booking_occurrence")
	}

	return rowsAff, nil
}

// DeleteAllG deletes all rows in the slice.
func (o BookingOccurrenceSlice) DeleteAllG(ctx context.Context) (int64, error) {
	return o.DeleteAll(ctx, boil.GetContextDB())
}

// DeleteAll deletes all rows in the slice, using an executor.
func (o BookingOccurrenceSlice) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if len(o) == 0 {
		return 0, nil
	}

	if len(bookingOccurrenceBeforeDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doBeforeDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	var args []interface{}
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), bookingOccurrencePrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "DELETE FROM \"ews\".\"booking_occurrence\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, bookingOccurrencePrimaryKeyColumns, len(o))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "appdb: unable to delete all from bookingOccurrence slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "appdb: failed to get rows affected by deleteall for booking_occurrence")
	}

	if len(bookingOccurrenceAfterDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	return rowsAff, nil
}

// ReloadG refetches the object from the database using the primary keys.
func (o *BookingOccurrence) ReloadG(ctx context.Context) error {
	if o == nil {
		return errors.New("appdb: no BookingOccurrence provided for reload")
	}

	return o.Reload(ctx, boil.GetContextDB())
}

// Reload refetches the object from the database
// using the primary keys with an executor.
func (o *BookingOccurrence) Reload(ctx context.Context, exec boil.ContextExecutor) error {
	ret, err := FindBookingOccurrence(ctx, exec, o.ID)
	if err != nil {
		return err
	}

	*o = *ret
	return nil
}

// ReloadAllG refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *BookingOccurrenceSlice) ReloadAllG(ctx context.Context) error {
	if o == nil {
		return errors.New("appdb: empty BookingOccurrenceSlice provided for reload all")
	}

	return o.ReloadAll(ctx, boil.GetContextDB())
}

// ReloadAll refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *BookingOccurrenceSlice) ReloadAll(ctx context.Context, exec boil.ContextExecutor) error {
	if o == nil || len(*o) == 0 {
		return nil
	}

	slice := BookingOccurrenceSlice{}
	var args []interface{}
	for _, obj := range *o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), bookingOccurrencePrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "SELECT \"ews\".\"booking_occurrence\".* FROM \"ews\".\"booking_occurrence\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, bookingOccurrencePrimaryKeyColumns, len(*o))

	q := queries.Raw(sql, args...)

	err := q.Bind(ctx, exec, &slice)
	if err != nil {
		return errors.Wrap(err, "appdb: unable to reload all in BookingOccurrenceSlice")
	}

	*o = slice

	return nil
}

// BookingOccurrenceExistsG checks if the BookingOccurrence row exists.
func BookingOccurrenceExistsG(ctx context.Context, iD int64) (bool, error) {
	return BookingOccurrenceExists(ctx, boil.GetContextDB(), iD)
}

// BookingOccurrenceExists checks if the BookingOccurrence row exists.
func BookingOccurrenceExists(ctx context.Context, exec boil.ContextExecutor, iD int64) (bool, error) {
	var exists bool
	sql := "select exists(select 1 from \"ews\".\"booking_occurrence\" where \"id\"=$1 limit 1)"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, iD)
	}
	row := exec.QueryRowContext(ctx, sql, iD)

	err := row.Scan(&exists)
	if err != nil {
		return false, errors.Wrap(err, "appdb: unable to check if booking_occurrence exists")
	}

	return exists, nil
}

// Exists checks if the BookingOccurrence row exists.
func (o *BookingOccurrence) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	return BookingOccurrenceExists(ctx, exec, o.ID)
}
